// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5v539ribqbq50Z1FYLegcomTxydYyohk',
    appId: '1:417690496068:web:3710350589db4ad6e16011',
    messagingSenderId: '417690496068',
    projectId: 'time-58bdf',
    authDomain: 'time-58bdf.firebaseapp.com',
    storageBucket: 'time-58bdf.appspot.com',
    measurementId: 'G-VQ8NP6G4PY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWAZHUKQfYHV14VbwQ0o9tH2ICYc012Zs',
    appId: '1:417690496068:android:ee274ca411c662e9e16011',
    messagingSenderId: '417690496068',
    projectId: 'time-58bdf',
    storageBucket: 'time-58bdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBicwmDhgKY9vy2oUQbpg2YQeGsgvk2ens',
    appId: '1:417690496068:ios:0dfa362a261162e1e16011',
    messagingSenderId: '417690496068',
    projectId: 'time-58bdf',
    storageBucket: 'time-58bdf.appspot.com',
    androidClientId: '417690496068-9djshhggjct2da43tobp8vkhp1g70vm1.apps.googleusercontent.com',
    iosClientId: '417690496068-3hftisk2cpclqdodq1o3g9j8nah2hp5v.apps.googleusercontent.com',
    iosBundleId: 'com.example.timecapsule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBicwmDhgKY9vy2oUQbpg2YQeGsgvk2ens',
    appId: '1:417690496068:ios:0dfa362a261162e1e16011',
    messagingSenderId: '417690496068',
    projectId: 'time-58bdf',
    storageBucket: 'time-58bdf.appspot.com',
    androidClientId: '417690496068-9djshhggjct2da43tobp8vkhp1g70vm1.apps.googleusercontent.com',
    iosClientId: '417690496068-3hftisk2cpclqdodq1o3g9j8nah2hp5v.apps.googleusercontent.com',
    iosBundleId: 'com.example.timecapsule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5v539ribqbq50Z1FYLegcomTxydYyohk',
    appId: '1:417690496068:web:7d2847a5bcf9376fe16011',
    messagingSenderId: '417690496068',
    projectId: 'time-58bdf',
    authDomain: 'time-58bdf.firebaseapp.com',
    storageBucket: 'time-58bdf.appspot.com',
    measurementId: 'G-0RXLK1C553',
  );

}